<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260626100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la table menu_image pour les images des menus';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE menu_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, menu_id INT NOT NULL, filename VARCHAR(255) NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_menu_image_menu ON menu_image (menu_id)');
        $this->addSql('ALTER TABLE menu_image ADD CONSTRAINT FK_menu_image_menu FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE menu_image DROP CONSTRAINT FK_menu_image_menu');
        $this->addSql('DROP TABLE menu_image');
    }
}
