parameters:
    app.email_verification_ttl_hours: 24
    app.password_reset_ttl_hours: 1

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Mail\MailerSendClient:
        arguments:
            $apiKey: '%env(MAILERSEND_API_KEY)%'

    App\Service\Auth\EmailVerificationTokenGenerator:
        arguments:
            $ttlHours: '%app.email_verification_ttl_hours%'

    App\Service\Auth\PasswordResetTokenGenerator:
        class: App\Service\Auth\EmailVerificationTokenGenerator
        arguments:
            $ttlHours: '%app.password_reset_ttl_hours%'
